title: Harrison Glenn
email: harrisonabglenn@gmail.com
description: >-
  I am Harrison Glenn, a student at the University of Sydney (USYD).
  I am fascinated by artificial intelligence, software development, and the art of testing software.
baseurl: ""
url: "https://harrymanual.github.io"
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed